/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function md2(buf: Buffer): string
export function md4(buf: Buffer): string
export function md5(buf: Buffer): string
export function sha1(buf: Buffer): string
export function sha256(buf: Buffer): string
export function sha512(buf: Buffer): string
export function sha2_256(buf: Buffer): string
export function sha2_512(buf: Buffer): string
export function sha3_256(buf: Buffer): string
export function sha3_512(buf: Buffer): string
export function sm3(buf: Buffer): string
export function belt_hash(buf: Buffer): string
export function blake2s256(buf: Buffer): string
export function blake2b512(buf: Buffer): string
export function blake3(buf: Buffer): string
export function fsb512(buf: Buffer): string
export function fsb256(buf: Buffer): string
export function gost94(buf: Buffer): string
export function groestl256(buf: Buffer): string
export function groestl512(buf: Buffer): string
export function ripemd128(buf: Buffer): string
export function ripemd160(buf: Buffer): string
export function ripemd256(buf: Buffer): string
export function ripemd320(buf: Buffer): string
export function shabal192(buf: Buffer): string
export function shabal224(buf: Buffer): string
export function shabal256(buf: Buffer): string
export function shabal384(buf: Buffer): string
export function shabal512(buf: Buffer): string
export function streebog256(buf: Buffer): string
export function streebog512(buf: Buffer): string
export function tiger(buf: Buffer): string
export function tiger2(buf: Buffer): string
export function whirlpool(buf: Buffer): string
