/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function md2(buf: Buffer): string
export function md4(buf: Buffer): string
export function md5(buf: Buffer): string
export function sha1(buf: Buffer): string
export function sha256(buf: Buffer): string
export function sha512(buf: Buffer): string
export function sha3_256(buf: Buffer): string
export function sm3(buf: Buffer): string
